# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-01-10 09:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Snack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='Wireless MAC Addr')),
                ('price', models.CharField(default='0', max_length=255, verbose_name='Slot')),
            ],
            options={
                'verbose_name': 'Snack',
                'verbose_name_plural': 'Snacks',
            },
        ),
    ]
