# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-01-10 11:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('head_count', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SnackDayMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('price_for_day', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='UserSnackDayMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('users_snack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='head_count.SnackDayMapping')),
            ],
        ),
        migrations.RemoveField(
            model_name='snack',
            name='price',
        ),
        migrations.AddField(
            model_name='snack',
            name='default_price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='snack',
            name='image_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='snack',
            name='name',
            field=models.CharField(max_length=255, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='snackdaymapping',
            name='snack_for_day',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='head_count.Snack'),
        ),
    ]
