# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-01-15 08:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('head_count', '0004_snack_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snack',
            name='image_url',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
