# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-01-24 10:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('head_count', '0007_newusermodel_unsubscribedusers'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NewUserModel',
            new_name='DefaultChoice',
        ),
    ]
